"""Read spell and mob lists from the prepared world for autocomplete.

The world is a Bylins MUD `small/` tree (KOI8-R), generated by the build
stage from `lib/` + `lib.template/`. We scan it once on first request and
cache in memory; the world doesn't change at runtime.

- Spells: `cfg/spells.xml` -- regex-grep over `<name rus="..." eng="..."/>`
  with `mode="kEnabled"` filtering. Doing a full XML parse is overkill
  for one tag and complicates the KOI8-R decoding.
- Mobs: `world/zones/*/mobs/*.yaml`, looking up `vnum:` and
  `names.aliases`/`names.nominative` for the display name.
"""

from __future__ import annotations

import os
import re
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import yaml as pyyaml

try:
    # libyaml C bindings -- 5-10x faster than the pure-Python loader, and
    # crucially releases the GIL during parse so ThreadPoolExecutor can
    # actually parallelise across files.
    from yaml import CSafeLoader as _SafeLoader  # type: ignore[attr-defined]
except ImportError:  # pragma: no cover -- fallback if libyaml isn't installed
    from yaml import SafeLoader as _SafeLoader

_PARSE_WORKERS = max(2, (os.cpu_count() or 4))


@dataclass(frozen=True)
class Spell:
    rus: str
    eng: str

    def matches(self, query: str) -> bool:
        q = query.lower()
        return q in self.rus.lower() or q in self.eng.lower()


@dataclass(frozen=True)
class Mob:
    vnum: int
    name: str

    def matches(self, query: str) -> bool:
        q = query.lower()
        return q in self.name.lower() or q in str(self.vnum)


@dataclass(frozen=True)
class Apply:
    location: int
    location_name: str  # human-readable, e.g. "сила"
    modifier: int


@dataclass(frozen=True)
class Obj:
    vnum: int
    name: str
    obj_type: str  # kWeapon, kArmor, ...
    wear_flags: tuple[str, ...]
    applies: tuple[Apply, ...] = ()
    affect_flags: tuple[str, ...] = ()  # kHaste, kStoneHands, kInvisible, ...
    extra_flags: tuple[str, ...] = ()

    def matches(self, query: str) -> bool:
        q = query.lower()
        return q in self.name.lower() or q in str(self.vnum)

    def fits_slot(self, slot: str) -> bool:
        # slot is one of the keys in SLOT_FLAGS below (e.g. "wield"); we
        # check that *any* of the required wear-flags is present on the
        # item. Empty slot filter -> "any wearable".
        if not slot:
            return True
        flags = SLOT_FLAGS.get(slot, ())
        return any(f in self.wear_flags for f in flags)


# EApply int -> short human label. Mirrors enum EApply in
# src/gameplay/affects/affect_contants.h. Cover the ones that actually
# appear on equipment in this world; rare/legacy entries fall through
# to the generic "apply N".
APPLY_NAMES: dict[int, str] = {
    0: "—",
    1: "сила", 2: "ловк", 3: "ум", 4: "муд", 5: "тело", 6: "обая",
    9: "возр", 10: "вес", 11: "рост",
    12: "регмана", 13: "HP", 14: "движ", 15: "$",
    17: "AC", 18: "hitroll", 19: "damroll",
    20: "save:воля", 23: "save:крит", 24: "save:маг", 39: "save:рефл",
    21: "рез:огонь", 22: "рез:воздух", 46: "рез:вода", 47: "рез:земля",
    48: "рез:жизнь", 49: "рез:разум", 50: "рез:яд",
    25: "регHP", 26: "регдвиж",
    27: "1круг", 28: "2круг", 29: "3круг", 30: "4круг",
    31: "5круг", 32: "6круг", 33: "7круг", 34: "8круг", 35: "9круг",
    36: "размер", 37: "броня", 38: "яд",
    40: "успехкаст", 41: "морал", 42: "инициат", 43: "религия",
    44: "поглощ", 51: "рез:аффект", 52: "рез:маг.урон",
    62: "физ.рез", 63: "рез:тьма",
    65: "+опыт%", 66: "+физурон%", 67: "блинк:физ",
    68: "+магурон%", 69: "блинк:маг",
}


# Affect-flag string -> compact display label (русский).
AFFECT_FLAG_LABELS: dict[str, str] = {
    "kHaste": "ускорение",
    "kStoneHands": "каменные руки",
    "kWaterBreath": "дых.под.водой",
    "kFly": "полёт",
    "kBless": "доблесть",
    "kBlink": "мерцание",
    "kSanctuary": "святилище",
    "kAirShield": "возд.щит",
    "kFireShield": "огн.щит",
    "kIceShield": "лед.щит",
    "kMagicGlass": "зерк.магии",
    "kPrismaticAura": "призм.аура",
    "kHolyLight": "св.свет",
    "kHolyDark": "св.тьма",
    "kDetectAlign": "видеть.накл",
    "kDetectInvisible": "видеть.невид",
    "kDetectMagic": "видеть.магию",
    "kDetectLife": "видеть.жизнь",
    "kInfravision": "инфразрение",
    "kWaterWalk": "ход.по.воде",
    "kInvisible": "невидимость",
    "kSneak": "подкрад",
    "kHide": "укрытие",
    "kAirAura": "возд.аура",
    "kFireAura": "огн.аура",
    "kIceAura": "лед.аура",
    "kEarthAura": "зем.аура",
    "kCommander": "полководец",
    "kCombatLuck": "удача.в.бою",
    "kGodsShield": "бож.щит",
    "kSingleLight": "светильник",
    "kHaemorrhage": "кровотечение",
    "kSilence": "немота",
    "kSleep": "сон",
    "kCharmed": "чармис",
    "kHorse": "конь",
    "kCurse": "проклятие",
    "kPoisoned": "яд",
    "kBlind": "слепота",
    "kHold": "удержание",
    "kAwarness": "осторожность",
    "kVampirism": "вампиризм",
    "kBerserk": "ярость",
    "kFrenzy": "берсерк",
    "kBrokenChains": "разорв.цепи",
    "kForcesOfEvil": "силы.зла",
    "kHelper": "помощник",
}


# Slot key -> tuple of wear-flag strings the engine uses. Keys are stable
# identifiers we expose in the UI; values come from /opt/small/world YAML.
# kHold has overlap with kWield (you can hold a one-hand weapon in either
# hand), so we list it in both buckets and let the user pick.
SLOT_FLAGS: dict[str, tuple[str, ...]] = {
    "wield":  ("kWield", "kBoth"),
    "hold":   ("kHold", "kWield"),
    "shield": ("kShield",),
    "head":   ("kHead",),
    "body":   ("kBody",),
    "legs":   ("kLegs",),
    "feet":   ("kFeet",),
    "hands":  ("kHands",),
    "arms":   ("kArms",),
    "about":  ("kAbout",),
    "waist":  ("kWaist",),
    "wrist":  ("kWrist",),
    "neck":   ("kNeck",),
    "finger": ("kFinger",),
    "quiver": ("kQuiver",),
}

_spells_cache: list[Spell] | None = None
_mobs_cache: list[Mob] | None = None
_objs_cache: list[Obj] | None = None

_SPELL_NAME_RE = re.compile(
    rb'<name\s+rus="([^"]+)"\s+eng="([^"]+)"\s*/>'
)
_SPELL_DISABLED_RE = re.compile(rb'mode="kDisabled"')


def load_spells(world_dir: Path) -> list[Spell]:
    """Walk cfg/spells.xml, return enabled spells. Order preserved.

    The XML lives in KOI8-R; we read raw bytes and decode each captured
    chunk separately so a malformed tag elsewhere can't crash the load.
    """
    global _spells_cache
    if _spells_cache is not None:
        return _spells_cache

    path = world_dir / "cfg" / "spells.xml"
    if not path.is_file():
        _spells_cache = []
        return _spells_cache

    raw = path.read_bytes()
    # Split on `<spell ` to walk per-block; this lets us skip disabled
    # entries cleanly without a real XML parser.
    out: list[Spell] = []
    seen: set[str] = set()
    for block in raw.split(b"<spell ")[1:]:
        if _SPELL_DISABLED_RE.search(block):
            continue
        m = _SPELL_NAME_RE.search(block)
        if not m:
            continue
        try:
            rus = m.group(1).decode("koi8-r")
            eng = m.group(2).decode("koi8-r")
        except UnicodeDecodeError:
            continue
        if rus.startswith("!") or rus in seen:
            continue
        seen.add(rus)
        out.append(Spell(rus=rus, eng=eng))

    out.sort(key=lambda s: s.rus.lower())
    _spells_cache = out
    return out


def _parse_yaml_file(path: Path):
    """Open a KOI8-R YAML file and return parsed data, or None on error."""
    try:
        with path.open("rb") as fh:
            return pyyaml.load(fh.read().decode("koi8-r"), Loader=_SafeLoader)
    except Exception:  # noqa: BLE001
        return None


def load_mobs(world_dir: Path) -> list[Mob]:
    """Walk world/zones/*/mobs/*.yaml; index vnum + display name."""
    global _mobs_cache
    if _mobs_cache is not None:
        return _mobs_cache

    files: list[Path] = []
    zones_dir = world_dir / "world" / "zones"
    if zones_dir.is_dir():
        files = sorted(zones_dir.glob("*/mobs/*.yaml"))

    out: list[Mob] = []
    seen_vnums: set[int] = set()
    if files:
        with ThreadPoolExecutor(max_workers=_PARSE_WORKERS) as ex:
            for data in ex.map(_parse_yaml_file, files):
                if not isinstance(data, dict):
                    continue
                for entry in _iter_mob_entries(data):
                    vnum = entry.get("vnum")
                    if not isinstance(vnum, int) or vnum in seen_vnums:
                        continue
                    names = entry.get("names") or {}
                    name = (
                        names.get("aliases")
                        or names.get("nominative")
                        or "?"
                    )
                    if isinstance(name, str):
                        name = name.strip().splitlines()[0] if name else "?"
                    else:
                        name = "?"
                    seen_vnums.add(vnum)
                    out.append(Mob(vnum=vnum, name=name))

    out.sort(key=lambda m: m.vnum)
    _mobs_cache = out
    return out


def _iter_mob_entries(data: dict) -> Iterable[dict]:
    """Mob YAML files come in two shapes: a single mob (top-level vnum/names)
    or `{mobs: [...]}` from a zone bundle."""
    if "vnum" in data:
        yield data
        return
    mobs = data.get("mobs")
    if isinstance(mobs, list):
        for m in mobs:
            if isinstance(m, dict):
                yield m


def search_spells(world_dir: Path, query: str, limit: int = 25) -> list[Spell]:
    if not query:
        return load_spells(world_dir)[:limit]
    return [s for s in load_spells(world_dir) if s.matches(query)][:limit]


def search_mobs(world_dir: Path, query: str, limit: int = 25) -> list[Mob]:
    if not query:
        return load_mobs(world_dir)[:limit]
    return [m for m in load_mobs(world_dir) if m.matches(query)][:limit]


# Types that the engine actually equips at the wear-flag slot. Other kHands
# items like kWorm ("заточка / закалка" -- unimplemented in the enum, used as
# crafting-only) carry the kHands flag but EquipObj rejects them via
# invalid_no_class. We skip them in the autocomplete to spare users from
# selecting kit that just falls into inventory.
WEARABLE_OBJ_TYPES = {
    "kLightSource", "kWeapon", "kArmor", "kContainer",
    "kLightArmor", "kMediumArmor", "kHeavyArmor",
}


def load_objects(world_dir: Path) -> list[Obj]:
    """Walk world/zones/*/objects/*.yaml; index vnum + name + wear_flags.

    Same KOI8-R yaml format as mobs. Items without a wear_flags entry, or
    with only `kTake`, or whose `type` is not in WEARABLE_OBJ_TYPES are
    skipped -- we only care about kit the engine will actually equip.
    """
    global _objs_cache
    if _objs_cache is not None:
        return _objs_cache

    files: list[Path] = []
    zones_dir = world_dir / "world" / "zones"
    if zones_dir.is_dir():
        files = sorted(zones_dir.glob("*/objects/*.yaml"))

    out: list[Obj] = []
    seen: set[int] = set()
    if files:
        with ThreadPoolExecutor(max_workers=_PARSE_WORKERS) as ex:
            for data in ex.map(_parse_yaml_file, files):
                if not isinstance(data, dict):
                    continue
                for entry in _iter_obj_entries(data):
                    vnum = entry.get("vnum")
                    if not isinstance(vnum, int) or vnum in seen:
                        continue
                    wear = entry.get("wear_flags") or []
                    if not isinstance(wear, list):
                        continue
                    # Skip items that can only be picked up but not equipped.
                    wearable = [w for w in wear if isinstance(w, str) and w != "kTake"]
                    if not wearable:
                        continue
                    names = entry.get("names") or {}
                    name = (
                        (names.get("aliases") if isinstance(names, dict) else None)
                        or (entry.get("short_desc") if isinstance(entry.get("short_desc"), str) else None)
                        or "?"
                    )
                    if isinstance(name, str):
                        name = name.strip().splitlines()[0] if name else "?"
                    else:
                        name = "?"
                    obj_type = entry.get("type") if isinstance(entry.get("type"), str) else "?"
                    if obj_type not in WEARABLE_OBJ_TYPES:
                        continue
                    applies_raw = entry.get("applies") or []
                    applies: list[Apply] = []
                    if isinstance(applies_raw, list):
                        for ap in applies_raw:
                            if not isinstance(ap, dict):
                                continue
                            loc = ap.get("location")
                            mod = ap.get("modifier")
                            if not isinstance(loc, int) or not isinstance(mod, int) or mod == 0:
                                continue
                            applies.append(Apply(
                                location=loc,
                                location_name=APPLY_NAMES.get(loc, f"apply{loc}"),
                                modifier=mod,
                            ))
                    aff_raw = entry.get("affect_flags") or []
                    aff = tuple(f for f in aff_raw if isinstance(f, str)) if isinstance(aff_raw, list) else ()
                    extra_raw = entry.get("extra_flags") or []
                    extra = tuple(f for f in extra_raw if isinstance(f, str)) if isinstance(extra_raw, list) else ()
                    seen.add(vnum)
                    out.append(Obj(
                        vnum=vnum,
                        name=name,
                        obj_type=obj_type,
                        wear_flags=tuple(wearable),
                        applies=tuple(applies),
                        affect_flags=aff,
                        extra_flags=extra,
                    ))

    out.sort(key=lambda o: o.vnum)
    _objs_cache = out
    return out


def _iter_obj_entries(data: dict):
    if "vnum" in data:
        yield data
        return
    objs = data.get("objects") or data.get("objs")
    if isinstance(objs, list):
        for o in objs:
            if isinstance(o, dict):
                yield o


def search_objects(world_dir: Path, slot: str, query: str, limit: int = 25) -> list[Obj]:
    items = [o for o in load_objects(world_dir) if o.fits_slot(slot)]
    if query:
        items = [o for o in items if o.matches(query)]
    return items[:limit]


def get_object(world_dir: Path, vnum: int) -> Obj | None:
    """O(N) lookup over the cached list -- N=17k, fine for occasional UI calls."""
    for o in load_objects(world_dir):
        if o.vnum == vnum:
            return o
    return None


def obj_summary(o: Obj) -> str:
    """Compact one-line description of an item's bonuses, used for tooltips."""
    parts: list[str] = []
    for ap in o.applies:
        sign = "+" if ap.modifier >= 0 else ""
        parts.append(f"{sign}{ap.modifier} {ap.location_name}")
    for f in o.affect_flags:
        parts.append(AFFECT_FLAG_LABELS.get(f, f))
    return ", ".join(parts) if parts else "—"
