"""Read spell and mob lists from the prepared world for autocomplete.

The world is a Bylins MUD `small/` tree (KOI8-R), generated by the build
stage from `lib/` + `lib.template/`. We scan it once on first request and
cache in memory; the world doesn't change at runtime.

- Spells: `cfg/spells.xml` -- regex-grep over `<name rus="..." eng="..."/>`
  with `mode="kEnabled"` filtering. Doing a full XML parse is overkill
  for one tag and complicates the KOI8-R decoding.
- Mobs: `world/zones/*/mobs/*.yaml`, looking up `vnum:` and
  `names.aliases`/`names.nominative` for the display name.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from ruamel.yaml import YAML


@dataclass(frozen=True)
class Spell:
    rus: str
    eng: str

    def matches(self, query: str) -> bool:
        q = query.lower()
        return q in self.rus.lower() or q in self.eng.lower()


@dataclass(frozen=True)
class Mob:
    vnum: int
    name: str

    def matches(self, query: str) -> bool:
        q = query.lower()
        return q in self.name.lower() or q in str(self.vnum)


_spells_cache: list[Spell] | None = None
_mobs_cache: list[Mob] | None = None

_SPELL_NAME_RE = re.compile(
    rb'<name\s+rus="([^"]+)"\s+eng="([^"]+)"\s*/>'
)
_SPELL_DISABLED_RE = re.compile(rb'mode="kDisabled"')


def load_spells(world_dir: Path) -> list[Spell]:
    """Walk cfg/spells.xml, return enabled spells. Order preserved.

    The XML lives in KOI8-R; we read raw bytes and decode each captured
    chunk separately so a malformed tag elsewhere can't crash the load.
    """
    global _spells_cache
    if _spells_cache is not None:
        return _spells_cache

    path = world_dir / "cfg" / "spells.xml"
    if not path.is_file():
        _spells_cache = []
        return _spells_cache

    raw = path.read_bytes()
    # Split on `<spell ` to walk per-block; this lets us skip disabled
    # entries cleanly without a real XML parser.
    out: list[Spell] = []
    seen: set[str] = set()
    for block in raw.split(b"<spell ")[1:]:
        if _SPELL_DISABLED_RE.search(block):
            continue
        m = _SPELL_NAME_RE.search(block)
        if not m:
            continue
        try:
            rus = m.group(1).decode("koi8-r")
            eng = m.group(2).decode("koi8-r")
        except UnicodeDecodeError:
            continue
        if rus.startswith("!") or rus in seen:
            continue
        seen.add(rus)
        out.append(Spell(rus=rus, eng=eng))

    out.sort(key=lambda s: s.rus.lower())
    _spells_cache = out
    return out


def load_mobs(world_dir: Path) -> list[Mob]:
    """Walk world/zones/*/mobs/*.yaml; index vnum + display name.

    Yaml files are KOI8-R, but ruamel.yaml handles encoding via the open
    mode -- we open as text with explicit encoding.
    """
    global _mobs_cache
    if _mobs_cache is not None:
        return _mobs_cache

    yaml = YAML(typ="safe")
    out: list[Mob] = []
    seen_vnums: set[int] = set()

    zones_dir = world_dir / "world" / "zones"
    if zones_dir.is_dir():
        for mob_file in sorted(zones_dir.glob("*/mobs/*.yaml")):
            try:
                with mob_file.open(encoding="koi8-r") as fh:
                    data = yaml.load(fh)
            except Exception:  # noqa: BLE001 -- skip malformed
                continue
            if not isinstance(data, dict):
                continue
            for entry in _iter_mob_entries(data):
                vnum = entry.get("vnum")
                if not isinstance(vnum, int) or vnum in seen_vnums:
                    continue
                names = entry.get("names") or {}
                name = (
                    names.get("aliases")
                    or names.get("nominative")
                    or "?"
                )
                if isinstance(name, str):
                    name = name.strip().splitlines()[0] if name else "?"
                else:
                    name = "?"
                seen_vnums.add(vnum)
                out.append(Mob(vnum=vnum, name=name))

    out.sort(key=lambda m: m.vnum)
    _mobs_cache = out
    return out


def _iter_mob_entries(data: dict) -> Iterable[dict]:
    """Mob YAML files come in two shapes: a single mob (top-level vnum/names)
    or `{mobs: [...]}` from a zone bundle."""
    if "vnum" in data:
        yield data
        return
    mobs = data.get("mobs")
    if isinstance(mobs, list):
        for m in mobs:
            if isinstance(m, dict):
                yield m


def search_spells(world_dir: Path, query: str, limit: int = 25) -> list[Spell]:
    if not query:
        return load_spells(world_dir)[:limit]
    return [s for s in load_spells(world_dir) if s.matches(query)][:limit]


def search_mobs(world_dir: Path, query: str, limit: int = 25) -> list[Mob]:
    if not query:
        return load_mobs(world_dir)[:limit]
    return [m for m in load_mobs(world_dir) if m.matches(query)][:limit]
